### PR TITLE
update import statements

### PR DESCRIPTION
**Pull request by aiqc**
old school imports in the tutorial were throwing warnings

### CODE REVIEW

**Comment by edmundhighcock** [comment]
Hi @aiqc, since you are clearly getting this to work, can I ask what version of JupyterHub you are using?

**Comment by aiqc** [comment]
Hi @edmundhighcock I am not using JupyterHub

**Comment by aiqc** [comment]
**Dependencies**
```
3.7.12 = python
2.2.0 = dash
0.4.1 = jupyter-dash
3.3.0 = jupyterlab
2.0.3 = Werkzeug
```

**Comment by edmundhighcock** [comment]
Understood, thanks very much!

**Review by alexcjohnson — APPROVED** [review]
Thanks very much @aiqc - some of these changes we were intentionally delaying so they'd still work with Dash 1.x, but at this point anyone using the `getting_started` notebook should be on Dash 2.x 💃

**Pull request merged**
