### PR TITLE
support async kernel in _request_jupyter_config

### LINKED ISSUE #62: can't run JupyterDash.infer_jupyter_proxy_config() in Jupyterhub
I am not able to run ` JupyterDash.infer_jupyter_proxy_config()` in Jupyterhub. There is no error message, cell remains in busy state without any output. Do you have any idea?

* `app.run_server()` returns `127.0.0.1:8005` which will not work from outside 
* `app.run_server("mode=jupyterlab")` also won't work 
*  I also see in the browser console: `blocked mixed content: the page was loaded over HTTPS, but requested an insecure frame 'http://ip:8050/'. This request has been blocked; the content must be served over HTTPS.`

only thing working is opening the ip:8050 in another tab and I can see the dashboard.

### PR DESCRIPTION
**Pull request by alexcjohnson**
Fix #62 - and a few other issues that seem to be hitting the same thing.

### CODE REVIEW

**Review by T4rk1n — APPROVED** [review]
:woman_dancing: Works nicely for me.

**Comment by gravelrider** [comment]
This is great news! Thank you @alexcjohnson!

Do you already have plans on when this fix will be part of the next release?

**Comment by alexcjohnson** [comment]
We were hoping to release yesterday, but this fix unfortunately doesn’t work in all environments. Still investigating…

**Comment by alexcjohnson** [comment]
Released v0.4.2 - please let us know with a new issue if there are still any issues.

**Pull request merged**
